name: benchmark

on: [push]

jobs:
  bench:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ["v1.x"]
    name: Run Benchmarks
    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: ${{ matrix.deno }}

      - run: make --always-make benchmark
