name: publish

on:
  create:
    ref_type: "tag"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.5.x

      - name: Publish module
        run: |
          deno install -A --unstable https://x.nest.land/eggs@0.3.2/eggs.ts
          eggs link ${{ secrets.NESTAPIKEY }}
          eggs publish --yes --no-check --version $(git describe --tags $(git rev-list --tags --max-count=1))
