name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: v1.x

      - name: Run tests
        run: deno test --allow-all --coverage=cov/

      - name: Create coverage report
        run: deno coverage --lcov cov/ > cov.lcov

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./cov.lcov
